<?php

use Magento\Framework\View\Element\Template;

/** @var Template $block */

?>
<div class="form-container">
    <input type="text"
           class="task-input-field"
           id="todo-task-input"
           name="task"
           value=""
           placeholder="Add a new task..."
    />
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button"
                    title="Add Task"
                    class="action save primary"
                    id="add-new-task-button">
                <span>Add Task</span>
            </button>
        </div>
    </div>
</div>
<div data-bind="scope: 'todo'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
        }
    }
</script>